name: aerodrop
description: "Drone Delivery Service Mobile Interface"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  flutter_svg: ^2.2.3
  flutter_screenutil: ^5.9.3
  flutter_map: ^8.2.2
  latlong2: ^0.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  flutter_gen_runner: ^5.12.0


flutter_gen:
  output: lib/generated/
  line_length: 120
  integrations:
    flutter_svg: true
    lottie: true


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/source_sans_pro/
    - assets/onboarding/
    - assets/svgs/

  fonts:
    - family: SourceCodePro
      fonts:
        # ExtraLight (Weight 200)
        - asset: assets/fonts/source_sans_pro/SourceCodePro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/source_sans_pro/SourceCodePro-ExtraLightItalic.ttf
          weight: 200
          style: italic

        # Light (Weight 300)
        - asset: assets/fonts/source_sans_pro/SourceCodePro-Light.ttf
          weight: 300
        - asset: assets/fonts/source_sans_pro/SourceCodePro-LightItalic.ttf
          weight: 300
          style: italic

        # Regular (Weight 400)
        - asset: assets/fonts/source_sans_pro/SourceCodePro-Regular.ttf
          weight: 400
        - asset: assets/fonts/source_sans_pro/SourceCodePro-Italic.ttf
          weight: 400
          style: italic

        # Medium (Weight 500)
        - asset: assets/fonts/source_sans_pro/SourceCodePro-Medium.ttf
          weight: 500
        - asset: assets/fonts/source_sans_pro/SourceCodePro-MediumItalic.ttf
          weight: 500
          style: italic

        # SemiBold (Weight 600)
        - asset: assets/fonts/source_sans_pro/SourceCodePro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/source_sans_pro/SourceCodePro-SemiBoldItalic.ttf
          weight: 600
          style: italic

        # Bold (Weight 700)
        - asset: assets/fonts/source_sans_pro/SourceCodePro-Bold.ttf
          weight: 700
        - asset: assets/fonts/source_sans_pro/SourceCodePro-BoldItalic.ttf
          weight: 700
          style: italic

        # ExtraBold (Weight 800)
        - asset: assets/fonts/source_sans_pro/SourceCodePro-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/source_sans_pro/SourceCodePro-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        # Black (Weight 900)
        - asset: assets/fonts/source_sans_pro/SourceCodePro-Black.ttf
          weight: 900
        - asset: assets/fonts/source_sans_pro/SourceCodePro-BlackItalic.ttf
          weight: 900
          style: italic