name: aerodrop
description: "Drone Delivery Service Mobile Interface"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.0.1
  flutter_svg: ^2.2.3
  flutter_screenutil: ^5.9.3
  flutter_map: ^8.2.2
  latlong2: ^0.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  flutter_gen_runner: ^5.12.0


flutter_gen:
  output: lib/generated/
  line_length: 120
  integrations:
    flutter_svg: true
    lottie: true


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/source_sans_pro/
    - assets/onboarding/
    - assets/svgs/

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/source_sans_pro/SourceSansPro-Regular.ttf
        - asset: assets/fonts/source_sans_pro/SourceSansPro-Italic.ttf
          style: italic
        - asset: assets/fonts/source_sans_pro/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/source_sans_pro/SourceSansPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/source_sans_pro/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/source_sans_pro/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/source_sans_pro/SourceSansPro-Black.ttf
          weight: 900